### PR TITLE
Add 405 Method Not Allowed detection

### PR DESCRIPTION
**Pull request by randohinn**
This PR enables to detect error 405's and return a proper response to unallowed methods.

### CODE REVIEW

**Comment by aljoni** [comment]
Instead of dying, it would be better if it would return an array as such:
```php
return [
  route: null,
  code: 405
];
```
This would be more preferable as it would then be possible to generate an error page from the error with a template or such.  Later on the application may also use plugins that record errors and such.

When a route is matched it should also now be returned as:
```php
return [
  route: $route
];
```

**Comment by randohinn** [comment]
Updated

**Comment by aljoni** [comment]
Yes, it would need to be changed.  Although this is a better solution this way.  I could re-structure it, unless you have some ideas?

**Comment by aljoni** [comment]
I'll have a look at re-structuring it.

**Comment by aljoni** [comment]
Need to merge before I close...

**Comment by aljoni** [comment]
There we go.

**Pull request merged**
